export const MOCK_DATA = {
  domain: 'ADMIN',
  structuralSubtypes: {
    FOOTER: {
      states: {
        FULL: [
          {
            role: 'admin',
            _id: '68d4186326641456d521c9fa',
            menuItemText: 'Help',
            routePath: '/help',
            sortId: 13,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'FOOTER',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-27T02:55:02.842Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4184c26641456d521c9f5',
            menuItemText: 'Legal',
            routePath: '/legal',
            sortId: 19,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'FOOTER',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-27T02:55:02.842Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4183526641456d521c9f1',
            menuItemText: 'About Us',
            routePath: '/about-us',
            sortId: 22,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'FOOTER',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-27T02:55:02.842Z',
            archived: false,
            __v: 0,
          },
        ],
      },
    },
    HEADER: {
      states: {
        COMPACT: [
          {
            role: 'admin',
            _id: '68d40a3b26641456d521c968',
            menuItemText: 'Admin Dashboard',
            routePath: '/admin-dashboard',
            sortId: 6,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'COMPACT',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-24T15:11:55.363Z',
            archived: false,
            __v: 0,
          },
        ],
        FULL: [
          {
            role: 'admin',
            _id: '68d097bb26641456d521c398',
            menuItemText: 'Admin Dashboard',
            routePath: '/admin-dashboard',
            sortId: 1,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 12,
            description: 'Something',
            lastUpdated: '2025-09-27T20:25:17.546Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'space_dashboard',
          },
          {
            role: 'admin',
            _id: '68d097e826641456d521c39c',
            menuItemText: 'Mfe Orchestrator',
            routePath: '/mfe-orchestrator',
            sortId: 1,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 5,
            description: 'No description provided',
            lastUpdated: '2025-09-25T21:33:47.871Z',
            archived: false,
            __v: 0,
            parentId: '68d03a5b26641456d521c2db',
            headerSvgPath: 'hub',
          },
          {
            role: 'admin',
            _id: '68d09d7926641456d521c401',
            menuItemText: 'Navigational List',
            routePath: '/navigational-list',
            sortId: 1,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 9,
            description: 'No description provided',
            lastUpdated: '2025-09-28T16:21:33.361Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'list',
            parentId: '68d03a5b26641456d521c2db',
          },
          {
            role: 'admin',
            _id: '68d0a48026641456d521c464',
            menuItemText: 'Workshop Creator',
            routePath: '/workshop-creator',
            sortId: 1,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 9,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:00:41.343Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'work',
            parentId: '68d0a3e126641456d521c45b',
          },
          {
            role: 'admin',
            _id: '68d09e3226641456d521c409',
            menuItemText: 'User Management',
            routePath: '/user-management',
            sortId: 2,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 9,
            description: 'No description provided',
            lastUpdated: '2025-09-28T16:20:45.708Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'group',
            parentId: '68d03a5b26641456d521c2db',
          },
          {
            role: 'admin',
            _id: '68d0a3e126641456d521c45b',
            menuItemText: 'Publisher',
            routePath: '/publisher',
            sortId: 2,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 2,
            description: 'No description provided',
            lastUpdated: '2025-09-25T21:33:47.871Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'publish',
          },
          {
            role: 'admin',
            _id: '68d0a41e26641456d521c461',
            menuItemText: 'Document Editor',
            routePath: '/document-editor',
            sortId: 2,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 17,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:12:45.370Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'description',
            parentId: '68d0a3e126641456d521c45b',
          },
          {
            role: 'admin',
            _id: '68d03a5b26641456d521c2db',
            menuItemText: 'Mission Controls',
            routePath: '/mission-controls',
            sortId: 3,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 4,
            description: 'asdfasdfasdf',
            lastUpdated: '2025-09-25T21:33:47.871Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'rocket_launch',
          },
          {
            role: 'admin',
            _id: '68d0a04426641456d521c418',
            menuItemText: 'MCP Settings',
            routePath: '/mcp-settings',
            sortId: 3,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 5,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:11:30.554Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'tune',
            parentId: '68d03a5b26641456d521c2db',
          },
          {
            role: 'admin',
            _id: '68d0a3f826641456d521c45e',
            menuItemText: 'Assignment Test',
            routePath: '/assignment-test',
            sortId: 3,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 12,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:01:12.107Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'assignment',
            parentId: '68d0a3e126641456d521c45b',
          },
          {
            role: 'admin',
            _id: '68d0a14e26641456d521c42e',
            menuItemText: 'Feature Toggle',
            routePath: '/feature-toggle',
            sortId: 4,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 7,
            description: 'No description provided',
            lastUpdated: '2025-09-28T16:21:59.366Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'toggle_on',
            parentId: '68d03a5b26641456d521c2db',
          },
          {
            role: 'admin',
            _id: '68d0a16926641456d521c431',
            menuItemText: 'Broadcast',
            routePath: '/broadcast',
            sortId: 5,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 5,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:11:33.282Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'campaign',
            parentId: '68d03a5b26641456d521c2db',
          },
          {
            role: 'admin',
            _id: '68d0a0e426641456d521c424',
            menuItemText: 'Frontstage',
            routePath: '/frontstage',
            sortId: 6,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 7,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:11:35.983Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'curtains',
            parentId: '68d03a5b26641456d521c2db',
          },
          {
            role: 'admin',
            _id: '68d0a05b26641456d521c41b',
            menuItemText: 'Backstage',
            routePath: '/backstage',
            sortId: 7,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 4,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:11:42.468Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'theater_comedy',
            parentId: '68d03a5b26641456d521c2db',
          },
          {
            role: 'admin',
            _id: '68d0a12b26641456d521c42b',
            menuItemText: 'Ball Of Yarn',
            routePath: '/ball-of-yarn',
            sortId: 8,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'FULL',
            version: 13,
            description: 'No description provided',
            lastUpdated: '2025-10-04T17:43:10.064Z',
            archived: false,
            __v: 0,
            headerSvgPath: 'do_not_step',
            parentId: '68d03a5b26641456d521c2db',
          },
        ],
        RELAXED: [
          {
            role: 'admin',
            _id: '68d409c826641456d521c95e',
            menuItemText: 'Mission Controls',
            routePath: '/mission-controls',
            sortId: 1,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'RELAXED',
            version: 4,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:08:12.901Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d409a926641456d521c959',
            menuItemText: 'Publisher',
            routePath: '/publisher',
            sortId: 2,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'RELAXED',
            version: 5,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:08:10.886Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4098226641456d521c955',
            menuItemText: 'Admin Dashboard',
            routePath: '/admin-dashboard',
            sortId: 3,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'HEADER',
            state: 'RELAXED',
            version: 3,
            description: 'No description provided',
            lastUpdated: '2025-09-28T01:08:02.320Z',
            archived: false,
            __v: 0,
          },
        ],
      },
    },
    NAV: {
      states: {
        COMPACT: [
          {
            role: 'admin',
            _id: '68d416b526641456d521c9de',
            menuItemText: 'Admin Dashboard',
            routePath: '/admin-dashboard',
            sortId: 12,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'COMPACT',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-24T16:05:09.788Z',
            archived: false,
            __v: 0,
          },
        ],
        FULL: [
          {
            _id: '68d413b526641456d521c98f',
            menuItemText: 'Document Editor',
            routePath: '/document-editor',
            sortId: 0,
            authRequired: false,
            parentId: '68d4137826641456d521c987',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 6,
            description: 'No description provided',
            lastUpdated: '2025-10-05T19:15:07.480Z',
            archived: false,
            __v: 0,
            role: 'admin',
          },
          {
            role: 'admin',
            _id: '68d4140126641456d521c99b',
            menuItemText: 'Mfe Orchestrator',
            routePath: '/mfe-orchestrator',
            sortId: 0,
            authRequired: false,
            parentId: '68d413e826641456d521c997',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4139c26641456d521c98b',
            menuItemText: 'Assignment Test',
            routePath: '/assignment-test',
            sortId: 1,
            authRequired: false,
            parentId: '68d4137826641456d521c987',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d413d126641456d521c993',
            menuItemText: 'Workshop Creator',
            routePath: '/workshop-creator',
            sortId: 1,
            authRequired: false,
            parentId: '68d4137826641456d521c987',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4142726641456d521c99f',
            menuItemText: 'Navigational List',
            routePath: '/navigational-list',
            sortId: 1,
            authRequired: false,
            parentId: '68d413e826641456d521c997',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4143b26641456d521c9a3',
            menuItemText: 'User Management',
            routePath: '/user-management',
            sortId: 2,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 2,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
            parentId: '68d413e826641456d521c997',
          },
          {
            role: 'admin',
            _id: '68d4144d26641456d521c9a7',
            menuItemText: 'Broadcast',
            routePath: '/broadcast',
            sortId: 3,
            authRequired: false,
            parentId: '68d413e826641456d521c997',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4148726641456d521c9ab',
            menuItemText: 'MCP Settings',
            routePath: '/mcp-settings',
            sortId: 4,
            authRequired: false,
            parentId: '68d413e826641456d521c997',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d414c326641456d521c9af',
            menuItemText: 'Feature Toggle',
            routePath: '/feature-toggle',
            sortId: 5,
            authRequired: false,
            parentId: '68d413e826641456d521c997',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d414e126641456d521c9b3',
            menuItemText: 'Backstage',
            routePath: '/backstage',
            sortId: 6,
            authRequired: false,
            parentId: '68d413e826641456d521c997',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4150626641456d521c9b7',
            menuItemText: 'Frontstage',
            routePath: '/frontstage',
            sortId: 7,
            authRequired: false,
            parentId: '68d413e826641456d521c997',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4133b26641456d521c97e',
            menuItemText: 'Admin Dashboard',
            routePath: '/admin-dashboard',
            sortId: 8,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4154426641456d521c9bb',
            menuItemText: 'Ball Of Yarn',
            routePath: '/ball-of-yarn',
            sortId: 8,
            authRequired: false,
            parentId: '68d413e826641456d521c997',
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4137826641456d521c987',
            menuItemText: 'Publisher',
            routePath: '/publisher',
            sortId: 21,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d413e826641456d521c997',
            menuItemText: 'Mission Controls',
            routePath: '/mission-controls',
            sortId: 24,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'FULL',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-25T22:17:44.014Z',
            archived: false,
            __v: 0,
          },
        ],
        RELAXED: [
          {
            role: 'admin',
            _id: '68d4163826641456d521c9cd',
            menuItemText: 'Admin Dashboard',
            routePath: '/admin-dashboard',
            sortId: 9,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'RELAXED',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-24T16:03:04.852Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4164d26641456d521c9d1',
            menuItemText: 'Publisher',
            routePath: '/publisher',
            sortId: 10,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'RELAXED',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-24T16:03:25.541Z',
            archived: false,
            __v: 0,
          },
          {
            role: 'admin',
            _id: '68d4166f26641456d521c9d5',
            menuItemText: 'Mission Controls',
            routePath: '/mission-controls',
            sortId: 11,
            authRequired: false,
            domain: 'ADMIN',
            structuralSubtype: 'NAV',
            state: 'RELAXED',
            version: 1,
            description: 'No description provided',
            lastUpdated: '2025-09-24T16:03:59.704Z',
            archived: false,
            __v: 0,
          },
        ],
      },
    },
  },
};
